name: Compile Example Servers

on:
  push:
    paths:
      - 'Examples/Hello World/Server/**'
      - 'Examples/Realtime/Server/**'
      - 'Examples/Tic Tac Toe/Server/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'Examples/Hello World/Server/**'
      - 'Examples/Realtime/Server/**'
      - 'Examples/Tic Tac Toe/Server/**'
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build 'Hello World' with Ant
      run: ant -noinput -buildfile 'Examples/Hello World/Server/build.xml'
    - name: Build 'Realtime' with Ant
      run: ant -noinput -buildfile 'Examples/Realtime/Server/build.xml'
    - name: Build 'Tic Tac Toe' with Ant
      run: ant -noinput -buildfile 'Examples/Tic Tac Toe/Server/build.xml'
