name: Compile Master Server

env:
  PROJECT_NAME: 'MasterServer'
  PROJECT_PATH: 'Master Server'

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Master Server/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Master Server/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile '${{ env.PROJECT_PATH }}/build.xml'
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_NAME }}
        path: ${{ env.PROJECT_PATH }}/MasterServer.jar
